server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka
